#!/bin/bash

## special variables

echo "All variables passed to the script :$@"
echo "Number of variables passed to the script :$#"
echo "First varaibles:$1"
echo "script name:$0"
echo "who is running the script:$USER"
echo "which directory:$PWD"
echo "Home directory:$HOME"
echo "PID of current running script:$$"