#!/bin/bash

## special variables

echo "All variables passed to the script :$@"
echo "Number of variables passed to the script :$#"
echo "First varaibles:$1"
echo "script name:$0"
echo "who is running the script:$USER"
echo "which directory:$PWD"
echo "Home directory:$HOME"
echo "PID of current running script:$$"
sleep 5 &
echo "PID of the background commnd running just now:$!"
wait $!
echo "Line number:$LINENO"
echo "script compelted in $SECONDS seconds"
echo "Random number:$RANDOM"
echo "status of previous command:$?"